<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include($viewpath.'partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include($viewpath."partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<h4 class="site-init inline">Period</h4>
	<a href="<?php echo geturl("admin/period") ?>" class="site-init action-btn pull-right">
		<i class="ion-ios-arrow-back fonts site-red"></i> Go Back</a>
		<hr>
		<div class="row">
		<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
		<?php endif ?>

		<h5 class="site-init text-center">Edit Period</h5> 

		<!-- ADD NEW DATABASE -->
		<form class="form-horizontal" method="post" action="">
			<div class="col-md-12" id="logindiv">
				<div class="col-md-12 nopad" id="pastetablediv">
				<div class="col-md-12 nopad" id="copytablediv">
					<div class="col-md-10 nopad" id="tablesbox">
					<input type="hidden" name="id" value="<?php echo $Period['id']?>" />
					<input type="text" class="form-control" name="period" required value="<?php echo $Period['period_name'] ?>" placeholder="Period"/>
					</div>
					
					<div class="col-md-10 nopad">
						<!-- ADD TABLE -->
						<select name="frequencyid" required class="form-control">
						<option value="">Frequency</option>
						<?php foreach($Frequencies as $frequency) :?>
						<option <?php echo ($Period['frequency_id'] == $frequency['id']) ? "selected" : "" ?> value="<?php echo $frequency['id'] ?>">
						<?php echo $frequency['frequency_data_name'] ?></option>
						<?php endforeach ?>
						</select>
					</div>

				</div>
				</div>
			</div>

			<div id="submitdiv" class="col-md-10">
				<button  class="btn button-custom btn-custom-two pull-right">Update Period</button>
			</div>
		</form>
		<!-- END DATABASE -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/footer.phtml') ?>
<!-- END FOOTER