<?php
$viewpath = config('view_path');
@include($viewpath.'partials/header.phtml')
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php @include($viewpath.'partials/frontmenu.phtml') ?>
<!--MENU SECTION END-->


<section id="contact" style="padding-top: 40px !important;">
<div class="container">
<!-- <div class="row text-center header animate-in" data-anim-type="fade-in-up">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

<h3>Contact Details </h3>
<hr />

</div>
</div> -->

<br>
<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
	<div class="row animate-in" data-anim-type="fade-in-up">
	
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="contact-wrapper">
	<h3>Address : </h3>
	<?php echo $Contact['address'] ?>
	</div>
	</div>
	
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="contact-wrapper">
	<h3>Quick Contact</h3>
	<?php echo $Contact['contact'] ?>
	</div>
	</div>
	
	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<div class="contact-wrapper">
	<h3>We Are Social</h3>
	<p>
	Connect with us.
	</p>
	<div class="social-below">
	<a href="<?php echo $Contact['facebook'] ?>" class="btn button-custom btn-custom-two ion-social-facebook"> Facebook</a>
	<a href="<?php echo $Contact['twitter'] ?>" class="btn button-custom btn-custom-two ion-social-twitter"> Twitter</a>
	<a href="<?php echo $Contact['google'] ?>" class="btn button-custom btn-custom-two ion-social-googleplus"> Google +</a>
	</div>
	</div>

	</div>
</div>

</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
	<div class="contact-wrapper" id="logindiv">
	<h3 class="text-center ">SEND US AN EMAIL</h3>
	<br>
	<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
			<br>
	<?php endif ?>
		<form class="form-horizontal" action="" method="POST">
			<div class="form-group">
				<label for="title" class="col-md-1 site-init text-center font12">Firstname</label>
				<div class="col-md-3">
				<input type="text" name="firstname" value="" class="form-control" required placeholder="Jane"/>
				</div>

				<label for="lastname" class="col-md-1 site-init text-center font12">Lastname</label>
				<div class="col-md-3">
				<input type="text" name="lastname" value="" class="form-control" required placeholder="Doe"/>
				</div>

				<label for="email" class="col-md-1 site-init text-center font12">Email</label>
				<div class="col-md-3">
				<input type="email" name="email" value="" class="form-control" required placeholder="example@email.com"/>
				</div>

			</div>

			<div class="form-group">
				<label for="subject" class="col-md-1 site-init text-center font12">Subject</label>
				<div class="col-md-7">
				<input type="text" name="subject" value="" class="form-control" required placeholder="A brief description..."/>
				</div>

				<label for="phone" class="col-md-1 site-init text-center font12">Phone</label>
				<div class="col-md-3">
				<input type="text" name="phone" value="" class="form-control numlock" required placeholder="2348012345678">
				</div>

				<div class="col-md-11 col-md-offset-1">
				<textarea class="form-control" style="height: 150px" name="message" required placeholder="Message..."></textarea>
				</div>
				
				<div class="pull-right col-md-3 text-right">
					<button href="#" class="btn button-custom btn-custom-two font12"><i class="ion-forward"></i> Send Us A Message</button>
				</div>
			</div>
<!-- 			<div class="form-group">
				
			</div> -->

		</form>
	</div>
</div>

</div>
</section>



<!-- FOOTER -->
<?php @include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER