<select data-placeholder="Select Frequency Of Data..." required class="chosentablesingle dfrequency" name="frequency" tabindex="3">
	<option value=""></option>
	<?php if(count($Frequencies) > 0) :?> 
	<?php foreach($Frequencies as $frequency) :?>
	<option data-caltype="<?php echo $frequency['date_type']?>" 
	data-id="<?php echo $frequency['frequency_id']?>" data-type="<?php echo strtolower($frequency['frequency_data_name']) ?>" 
	value="<?php echo strtoupper($frequency['frequency_data_name'].'::'.$frequency['code']) ?>">
	<?php echo strtoupper($frequency['frequency_data_name']) ?></option> 
	 <?php endforeach ?> 
	<?php endif ?>
</select>