<?php
$viewpath = config('view_path');
@include($viewpath.'partials/header.phtml')
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php @include($viewpath.'partials/frontmenu.phtml') ?>
<!--MENU SECTION END-->

<!--SERVICE SECTION START-->

<section id="services">
<div class="container">
    <div class="row animate-in margin-top-4" data-anim-type="fade-in-up">
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4" id="datalistarea">
            <?php include($viewpath.'partials/databaselist.phtml') ?>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5" id="requestarea">
            <div class="services-wrapper overviewdivbox" id="financeplace">
            <h3><i class="ion-android-checkbox-outline"></i> Data Selection</h3>

                <?php if(isset($notification) && !empty($notification)) :?>
                    <div class="alert alert-warning alert-dismissible anasatnotification" role="alert">
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <i class="ion-information-circled anasatnotificationfont"></i> <?php echo $notification ?>
                    </div>
                <?php endif ?>

                <div class="col-md-12" id="empty">
                    <div class="alert alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <i class="ion-ios-information-outline info" id="indexinfo"></i> Kindly Select From Database To Request Data
                    </div>
                </div>

                <?php include($viewpath.'partials/requestform.phtml') ?>
            </div>

            <?php include($viewpath.'partials/clientform.phtml') ?>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3" id="overviewarea">
            <?php include($viewpath.'partials/requestoverview.phtml') ?>
        </div>

        <div class="row">
            <?php include($viewpath.'partials/clientoverview.phtml') ?>
        </div>

    </div>

</div>


</div>
</div>


<?php include($viewpath.'partials/prompts.phtml') ?>

</section>


<!-- FOOTER -->
<?php include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER -->