<?php
$viewpath = config('view_path');
@include($viewpath.'partials/header.phtml')
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php @include($viewpath.'partials/frontmenu.phtml') ?>
<!--MENU SECTION END-->

<!--SERVICE SECTION START-->

<section id="services">
    <div class="container">
        <div class="row animate-in margin-top-4" data-anim-type="fade-in-up">
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <?php include($viewpath.'partials/databaselist.phtml') ?>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5" id="requestarea">
                <div class="services-wrapper" id="financeplace">
                    <h3><i class="ion-pie-graph"></i>Select From Sub-Sectors</h3>
                    <a href="<?php echo geturl("/") ?>" class="btn button-custom btn-custom-two pull-right ion-home fonts">
                        &nbsp; Return Home</a>

                    <?php include($viewpath.'partials/notification.phtml') ?>

                    <div class="col-md-12 nopad" id="empty">

                        <ul class="sectorslist">
                            <?php if(!empty($Sectors)) :?>
                                <hr>
                                <?php foreach($Sectors as $data) :?>
                                    <li>
                                        <a href="<?php echo geturl("surveyresearch/{$data['id']}/sectors") ?>" class="dart site-init surveydata">
                                            <?php echo $data['name'] ?></a>
                                        <span class="ion-android-arrow-dropright pull-left site-purple question"></span>
                                    </li>
                                <?php endforeach?>
                            <?php endif ?>
                        </ul>
                    </div>

                    <?php include($viewpath.'partials/requestform.phtml') ?>
                </div>

                <?php include($viewpath.'partials/clientform.phtml') ?>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <?php include($viewpath.'partials/requestoverview.phtml') ?>
            </div>

            <div class="row">
                <?php include($viewpath.'partials/clientoverview.phtml') ?>
            </div>

        </div>

    </div>


    </div>
    </div>


    <?php include($viewpath.'partials/prompts.phtml') ?>

</section>


<!-- FOOTER -->
<?php include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER -->