<?php
$viewpath = config('view_path');
@include($viewpath.'partials/header.phtml')
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php @include($viewpath.'partials/frontmenu.phtml') ?>
<!--MENU SECTION END-->

<!--SERVICE SECTION START-->

<section id="services">
    <div class="container">
        <div class="row animate-in margin-top-4" data-anim-type="fade-in-up">
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <?php include($viewpath.'partials/databaselist.phtml') ?>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5" id="requestarea">
                <div class="services-wrapper" id="financeplace">
                    <h3 class="text-center"> Select To Download </h3>
                    <a href="<?php echo geturl("surveyresearch") ?>" class="btn button-custom btn-custom-two pull-right ion-ios-arrow-back fonts">
                    &nbsp; Return Back</a>


                    <div class="col-md-12 nopad" id="empty">
                        <?php if(!empty($Surveys)) :?>
                            
                            <hr>

                            <ul class="sectorslist">
                                <?php foreach($Surveys as $data) :?>
                                    <li>
                                        <a title="Click to download file" href="<?php echo geturl('download.php?action=download&filename='.$data['pathname']) ?>"
                                           class="dart site-init surveydata">
                                            <?php echo $data['filename'] ?></a>
                                        <span class="ion-ios-download-outline pull-left site-purple question"></span>
                                    </li>
                                <?php endforeach?>
                            </ul>
                        <?php else:?>
                            <br>
                            <?php include($viewpath.'partials/notification.phtml') ?>
                        <?php endif ?>
                    </div>

                    <?php include($viewpath.'partials/requestform.phtml') ?>
                </div>

                <?php include($viewpath.'partials/clientform.phtml') ?>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
                <?php include($viewpath.'partials/requestoverview.phtml') ?>
            </div>

            <div class="row">
                <?php include($viewpath.'partials/clientoverview.phtml') ?>
            </div>

        </div>

    </div>


    </div>
    </div>


    <?php include($viewpath.'partials/prompts.phtml') ?>

</section>


<!-- FOOTER -->
<?php include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER -->