<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include($viewpath.'partials/affiliateheader.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container nopad">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">


<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 nopad">
	<div class="services-wrapper">
			<div class="row dash-row">
            <?php include($viewpath.'partials/notification.phtml') ?>
			<div class="col-md-12 theaders">
					<!-- START Databases -->
					<div class="col-md-1 text-left site-red font10">
					S/N
					</div>
					<div class="col-md-2 text-left site-red font10">
					NAME OF REQUESTER
					</div>
					
					<div class="col-md-2 site-red font10">
					DESIGNATION
					</div>

					<div class="col-md-2 site-red font10">
					DATE/TIME
					</div>

					<div class="col-md-1 site-red font10">
					APPROVAL
					</div>
					
					<div class="col-md-1 site-red font10">
					DELIVERY
					</div>

					<div class="col-md-1 site-red font10">
					DATA-SIZE
					</div>

					<div class="col-md-1 site-red font10">
					BALANCE
					</div>

					<div class="col-md-1 site-red font10">
					ACTIONS
					</div>
			</div>

			<?php foreach($Requests as $key => $request): ?>
			<div class="col-md-12 tdbody">
					<!-- START Databases -->
					<div class="col-md-1 text-left site-red font10">
					<?php echo $key + 1?>
					</div>

					<div class="col-md-2 text-left site-init font10">
					<?php echo $request['name'] ?>
					</div>

					<div class="col-md-2 site-init font10">
					<?php echo $request['position_instituition'] ?>
					</div>
					
					<div class="col-md-2 site-init font10">
					<?php echo format_date($request['created_at'],'d M Y h:i:s') ?>
					</div>

					<div class="col-md-1 font10 
					<?php echo ($request['approved'] == 'awaiting') ? 'site-blue' : (($request['approved'] == 'approved') ? 'green' : 'site-red') ?> ">
					<?php echo ucfirst($request['approved']) ?>
					</div>
					
					<div class="col-md-1 site-init font10">
					<?php echo ($request['delivery'] == 0) ? "No" : "Yes"  ?>
					</div>

					<div class="col-md-1 site-init font10">
					<?php echo ($request['datasize']) ? $request['datasize'].'(kb)' : "NIL" ?>
					</div>

					<div class="col-md-1 site-init font10">
					<?php echo ($request['balance_after']) ? $request['balance_after'].'(kb)' : "NIL" ?>
					</div>

					<div class="col-md-1 site-init font10">
					<a title="view"  href="<?php echo geturl("affiliate/view/{$request['transactionid']}" ) ?>" class="site-init action-btn">
					<i class="ion-ios-eye-outline fonts site-red"></i>
					</a>
					</div>

			</div>
			<?php endforeach ?>
			
			<?php if(!empty($Requests)) :?>

			<div class="col-md-12">
				<?php echo $Links ?>
			</div>
			<?php else :?>
			<div class="col-md-12">
			  <div class="notify row">Requests List Empty!</div>
			</div>
			<?php endif ?>

		</div>
		<!-- END Databases -->
	</div>

	<br>


	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER