<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include($viewpath.'partials/affiliateheader.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<section id="services" >
<div class="container nopad">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in margin-top-4" data-anim-type="fade-in-up">


<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 nopad">
	<div class="services-wrapper">
			<div class="row dash-row">
            <?php include($viewpath.'partials/notification.phtml') ?>
					<!-- START Databases -->
					<table class="table table-bordered site-init">
						<thead>
						<th>
							S/N
						</th>

						<th>
							NAME OF REQUESTER
						</th>

						<th>
							DESIGNATION
						</th>

						<th>
							DATE/TIME
						</th>

						<th>
							APPROVAL
						</th>

						<th>
							DELIVERY
						</th>

						<th>
							DATA-SIZE
						</th>

						<th>
							BALANCE
						</th>

						<th>
							ACTIONS
						</th>
						</thead>

						<tbody>
						<?php foreach($Requests as $key => $request): ?>
						<tr>
							<td>
								<?php
								echo !empty($_GET['page']) || !empty($_GET['count']) ? ($_GET['page'] * $count = $_GET['count']) - $count + ($key + 1) : $key + 1
								?>
							</td>

							<td>
								<?php echo $request['name'] ?>
							</td>

							<td>
								<?php echo $request['position_instituition'] ?>
							</td>

							<td>
								<?php echo format_date($request['created_at'],'d M Y h:i:s') ?>
							</td>

							<td class="<?php echo ($request['approved'] == 'awaiting') ? 'site-blue' : (($request['approved'] == 'approved') ? 'green' : 'site-red') ?> ">
								<?php echo ucfirst($request['approved']) ?>
							</td>

							<td>
								<?php echo ($request['delivery'] == 0) ? "No" : "Yes"  ?>
							</td>

							<td>
								    <?php echo ($request['data']) ? $request['data'].'(kb)' : $request['data'] ?>
							</td>

							<td>
								<?php echo ($request['balance_after'] != "") ? $request['balance_after'].'(kb)' : "NIL" ?>
							</td>

							<td>
								<a title="view"  href="<?php echo geturl("affiliate/view/{$request['transactionid']}" ) ?>" class="site-init action-btn">
									<i class="ion-ios-eye-outline fonts site-red"></i>
								</a>
							</td>
						</tr>
						<?php endforeach ?>

						</tbody>
					</table>

			<!--Display Pagination Links Or notification If Request List Is Empty-->
			<?php if(!empty($Requests)) :?>
			<div class="col-md-12 nopad">
				<?php echo $Links ?>
			</div>
			<?php endif ?>

		</div>
	</div>

	</div>
</div>



</div>
</div>
</section>


<!-- FOOTER -->
<?php @include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER