<div class="services-wrapper">
	<h4 class=""><i class="ion-android-menu menui"></i> MENUS</h4>
	<hr style="margin-top:10px;margin-bottom:5px"/>
	<br>
	<a  href="<?php echo geturl('admin/dashboard') ?>" class="site-init admin-menu <?php echo (adminpageis('dashboard')) ? 'activated' : '' ?>">
	<i class="ion-android-apps site-red"></i> Dashboard</a>
	<hr class="no-margin">
	<a  href="<?php echo geturl('admin/affiliate') ?>" class="site-init admin-menu <?php echo (adminpageis('affiliate')) ? 'activated' : '' ?>">
	<i class="ion-briefcase"></i> Affiliates</a>
	<hr class="no-margin">
<!--	<a  href="--><?php //echo geturl('admin/clients') ?><!--" class="site-init admin-menu --><?php //echo (adminpageis('clients')) ? 'activated' : '' ?><!--">-->
<!--	<i class="ion-android-people"></i> Clients</a>-->
<!--	<hr class="no-margin">-->
	<a  href="<?php echo geturl('admin/requests') ?>" class="site-init admin-menu <?php echo (adminpageis('requests')) ? 'activated' : '' ?>">
	<i class="ion-clipboard"></i>Client Requests</a>
	<hr class="no-margin">
	<a  href="<?php echo geturl('admin/database') ?>" class="site-init admin-menu <?php echo (adminpageis('database')) ? 'activated' : '' ?>">
	<i class="ion-social-buffer-outline"></i> Databases</a>
	<hr class="no-margin">
	<a  href="<?php echo geturl('admin/tables') ?>" class="site-init admin-menu <?php echo (adminpageis('tables')) ? 'activated' : '' ?>">
	<i class="ion-android-checkbox-blank"></i> Tables</a>
	<hr class="no-margin">
	<a  href="<?php echo geturl('admin/levelaggregation') ?>" class="site-init admin-menu <?php echo (adminpageis('levelaggregation')) ? 'activated' : '' ?>">
	<i class="ion-android-checkbox-blank"></i> Level Of Aggregation</a>
	<hr class="no-margin">
	<a  href="<?php echo geturl('admin/categoryaggregation') ?>" class="site-init admin-menu <?php echo (adminpageis('categoryaggregation')) ? 'activated' : '' ?>">
	<i class="ion-android-checkbox-blank"></i> Category Of Aggregation</a>
	<hr class="no-margin">
	<a  href="<?php echo geturl('admin/frequency') ?>" class="site-init admin-menu <?php echo (adminpageis('frequency')) ? 'activated' : '' ?>">
	<i class="ion-android-checkbox-blank"></i> Frequency</a>
	<hr class="no-margin">
	<a  href="<?php echo geturl('admin/variables') ?>" class="site-init admin-menu <?php echo (adminpageis('variables')) ? 'activated' : '' ?>">
	<i class="ion-android-checkbox-blank"></i> Variables</a>
	<a  href="<?php echo geturl('admin/survey') ?>" class="site-init admin-menu <?php echo (adminpageis('survey')) ? 'activated' : '' ?>">
	<i class="ion-android-search"></i> Survey Research</a>
	<a  href="<?php echo geturl('admin/users') ?>" class="site-init admin-menu <?php echo (adminpageis('users')) ? 'activated' : '' ?>">
	<i class="ion-ios-people"></i> Manage Users</a>
	<a  href="<?php echo geturl('admin/subscriptions') ?>" class="site-init admin-menu <?php echo (adminpageis('subscriptions')) ? 'activated' : '' ?>">
		<i class="ion-cash"></i> Subscription </a>
	<a  href="<?php echo geturl('admin/condition') ?>" class="site-init admin-menu <?php echo (adminpageis('condition')) ? 'activated' : '' ?>">
		<i class="ion-document-text"></i> Terms &amp; Condition </a>
	</div>