<!DOCTYPE html>
<html lang="en" class="no-js" >
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<meta name="description" content="" />
<meta name="author" content="" />
<!--[if IE]>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<![endif]-->
<title>ANASTAT</title>
<link href="<?php echo geturl('assets/css/bootstrap.css') ?>" rel="stylesheet" />
<!-- ION ICONS STYLES -->
<link href="<?php echo geturl('assets/css/ionicons.css') ?>" rel="stylesheet" />
<!-- FONT AWESOME ICONS STYLES -->
<link href="<?php echo geturl('assets/css/font-awesome.css') ?>" rel="stylesheet" />
<!-- FANCYBOX POPUP STYLES -->
<link href="<?php echo geturl('assets/js/source/jquery.fancybox.css') ?>" rel="stylesheet" />
<!-- STYLES FOR VIEWPORT ANIMATION -->
<link href="<?php echo geturl('assets/css/animations.min.css') ?>" rel="stylesheet" />
<!-- CUSTOM CSS -->
<link href="<?php echo geturl('assets/css/style-solid-black.css') ?>" rel="stylesheet" />

<link href="<?php echo geturl('assets/css/overide.css') ?>" rel="stylesheet" />

<!-- Chosen -->
<link href="<?php echo geturl('assets/chosen/chosen.min.css') ?>" rel="stylesheet" />

<link rel="stylesheet" href="<?php echo geturl('assets/font-awesome/css/font-awesome.min.css') ?>">

<!-- HTML5 Shiv and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#menu-section">
<!--MENU SECTION START-->
<div class="navbar navbar-inverse navbar-fixed-top scroll-me" id="menu-section" >
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">
<?php echo (!empty($environment) && $environment == 'affiliate') ? ucfirst(affiliate('affiliate_name')) : 'ADMIN MANAGER' ?> 

</a>
</div>

<!-- REQUEST DELETE CONFIRM BOX -->
<div class="modal fade" id="deletePromptAdmin" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
       <h5 class="site-init"> Are you sure you want to perform delete?</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default site-red" data-dismiss="modal">No Thanks!</button>
        <a type="button" href="#" class="btn btn-default green">Yes</a>
      </div>
    </div>
  </div>
</div>