<div class="col-md-12 nopad hide" id="clientsoverview">
<div class="col-md-12 nopad" id="clientsoverview">
<br>
<h5 class="client-title site-init no-margin" style="">USER DETAILS</h5>
    <!-- Table OVERVIEW -->
    <div class="col-md-12" id="cl_name_overview">
        <h5 class="site-red font12">Name</h5>
        <span class="content site-init"></span>
        <hr class="splitter"/>
    </div>

    <!-- Level of Aggregation -->
    <div class="col-md-12" id="cl_sex_overview">
        <h5 class="site-red font12">Sex</h5>
        <span class="content site-init"></span>
        <hr class="splitter"/>
    </div>

    <!-- Cateory of Aggregation -->
    <div class="col-md-12" id="cl_email_overview">
        <h5 class="site-red font12">Email</h5>
        <span class="content site-init"></span>
        <hr class="splitter"/>
    </div>

    <!-- Cateory of Aggregation -->
    <div class="col-md-12" id="cl_add_overview">
        <h5 class="site-red font12">Address</h5>
        <span class="content site-init"></span>
        <hr class="splitter"/>
    </div>

    <!-- Variables -->
    <div class="col-md-12" id="cl_phone_overview">
        <h5 class="site-red font12">Telephone</h5>
        <span class="content site-init"></span>
        <hr class="splitter"/>
    </div>

    <!-- Variables -->
    <div class="col-md-12 hide" id="cl_institution_overview">
        <h5 class="site-red font12"> Institutional affiliation</h5>
        <span class="content site-init"></span>
        <hr class="splitter"/>
    </div>

    <!-- DATBASE OVERVIEW -->
    <div class="col-md-12" id="cl_designation_overview">
        <h5 class="site-red font12">Designation</h5>
        <span class="content site-init"></span>
        <hr class="splitter"/>
    </div>

</div>