<!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME -->
<!-- CORE JQUERY -->
<script src="<?php echo geturl('assets/js/jquery-1.11.1.js') ?>"></script>
<!-- BOOTSTRAP SCRIPTS -->
<script src="<?php echo geturl('assets/js/bootstrap.js') ?>"></script>
<!-- EASING SCROLL SCRIPTS PLUGIN -->
<script src="<?php echo geturl('assets/js/vegas/jquery.vegas.min.js') ?>"></script>
<!-- VEGAS SLIDESHOW SCRIPTS -->
<script src="<?php echo geturl('assets/js/jquery.easing.min.js') ?>"></script>
<!-- FANCYBOX PLUGIN -->
<script src="<?php echo geturl('assets/js/source/jquery.fancybox.js') ?>"></script>
<!-- ISOTOPE SCRIPTS -->
<script src="<?php echo geturl('assets/js/jquery.isotope.js') ?>"></script>
<!-- VIEWPORT ANIMATION SCRIPTS   -->
<script src="<?php echo geturl('assets/js/appear.min.js') ?>"></script>
<script src="<?php echo geturl('assets/js/animations.min.js') ?>"></script>
<!-- CUSTOM SCRIPTS -->
<script src="<?php echo geturl('assets/js/custom-solid.js') ?>"></script>

<script src="<?php echo geturl('assets/chosen/chosen.jquery.min.js') ?>"></script>

<script src="<?php echo geturl('assets/select2/js/select2.min.js') ?>"></script>

<script src="<?php echo geturl('assets/tinymce/tinymce.min.js') ?>"></script>

<script src="<?php echo geturl('assets/jquery-ui/jquery-ui.min.js') ?>"></script>

<!--PerfectScroll-->
<script src="<?php echo geturl('assets/perfect-scrollbar/js/perfect-scrollbar.js') ?>"></script>

<!--AlertifyJS-->
<script src="<?php echo geturl('assets/alertifyjs/alertify.min.js') ?>"></script>

<!--PACEJS-->
<script src="<?php echo geturl('assets/pace/pace.js') ?>"></script>

<script src="<?php echo geturl('assets/js/anastat/bootstrap.js') ?>"></script>
<script src="<?php echo geturl('assets/js/anastat/mixings.js') ?>"></script>
<script src="<?php echo geturl('assets/js/anastat/database.js') ?>"></script>
<script src="<?php echo geturl('assets/js/anastat/request.js') ?>"></script>
<script src="<?php echo geturl('assets/js/anastat/script.js') ?>"></script>

</body>

</html>