<!DOCTYPE html>
<html lang="en" class="no-js" >
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<meta name="description" content="" />
<meta name="author" content="" />

<title>ANASTAT</title>
<!-- BOOTSTRAP CORE CSS -->
<link href="<?php echo geturl('assets/css/bootstrap.css') ?>" media="all" rel="stylesheet" />
<!-- ION ICONS STYLES -->
<link href="<?php echo geturl('assets/css/ionicons.css') ?>" media="all" rel="stylesheet" />
<!-- FONT AWESOME ICONS STYLES -->
<link href="<?php echo geturl('assets/css/font-awesome.css') ?>" media="all" rel="stylesheet" />
<!-- FANCYBOX POPUP STYLES -->
<link href="<?php echo geturl('assets/js/source/jquery.fancybox.css') ?>" media="all" rel="stylesheet" />
<!-- STYLES FOR VIEWPORT ANIMATION -->
<link href="<?php echo geturl('assets/css/animations.min.css') ?>" media="all" rel="stylesheet" />
<!-- CUSTOM CSS -->
<link href="<?php echo geturl('assets/css/style-solid-black.css') ?>" media="all" rel="stylesheet" />

<link href="<?php echo geturl('assets/css/overide.css') ?>" media="all" rel="stylesheet" />

<!-- Chosen -->
<link href="<?php echo geturl('assets/chosen/chosen.min.css') ?>" rel="stylesheet" />
<!--  Select2-->
<link href="<?php echo geturl('assets/select2/css/select2.min.css') ?>" rel="stylesheet" />

<link rel="stylesheet" href="<?php echo geturl('assets/jquery-ui/jquery-ui.min.css') ?>">
<!--  Alertify.js-->
<link rel="stylesheet" href="<?php echo geturl('assets/alertifyjs/css/alertify.min.css') ?>">

<link rel="stylesheet" href="<?php echo geturl('assets/alertifyjs/css/themes/default.css') ?>">

<!-- Perfect Scroll-->
<link rel="stylesheet" href="<?php echo geturl('assets/perfect-scrollbar/css/perfect-scrollbar.min.css') ?>">

<!-- PaceJS-->
<link rel="stylesheet" href="<?php echo geturl('assets/pace/themes/white/pace-theme-flash.css') ?>">


<!-- HTML5 Shiv and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- IF JS IS NOT ENABLED -->
<noscript>

  <META HTTP-EQUIV="Refresh" CONTENT="0;URL=<?php echo geturl('jserror?jserror=enablejs') ?>">

</noscript>
<!-- End Check -->

</head>
<body data-spy="scroll" data-anim-type="fade-in-up" data-target="#menu-section" class="">
<!--MENU SECTION START-->
<div class="navbar navbar-inverse navbar-fixed-top scroll-me" id="menu-section" >
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">

ANASTAT

</a>
</div>