<!DOCTYPE html>
<html lang="en" class="no-js" >
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<meta name="description" content="" />
<meta name="author" content="" />
<!--[if IE]>
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<![endif]-->
<title>ANASTAT</title>
<!-- BOOTSTRAP CORE CSS -->
<link href="assets/css/bootstrap.css" media="all" rel="stylesheet" />
<!-- ION ICONS STYLES -->
<link href="assets/css/ionicons.css" media="all" rel="stylesheet" />
<!-- FONT AWESOME ICONS STYLES -->
<link href="assets/css/font-awesome.css" media="all" rel="stylesheet" />
<!-- FANCYBOX POPUP STYLES -->
<link href="assets/js/source/jquery.fancybox.css" media="all" rel="stylesheet" />
<!-- STYLES FOR VIEWPORT ANIMATION -->
<link href="assets/css/animations.min.css" media="all" rel="stylesheet" />
<!-- CUSTOM CSS -->
<link href="assets/css/style-solid-black.css" media="all" rel="stylesheet" />

<link href="assets/css/overide.css" media="all" rel="stylesheet" />

<!-- Chosen -->
<link href="assets/chosen/chosen.min.css" rel="stylesheet" />

<link rel="stylesheet" href="assets/jquery-ui/jquery-ui.min.css">

<!-- HTML5 Shiv and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- IF JS IS NOT ENABLED -->
<noscript>

  <META HTTP-EQUIV="Refresh" CONTENT="0;URL=<?php echo geturl('jserror?jserror=enablejs') ?>">

</noscript>
<!-- End Check -->

</head>
<body data-spy="scroll" data-target="#menu-section">
<!--MENU SECTION START-->
<div class="navbar navbar-inverse navbar-fixed-top scroll-me" id="menu-section" >
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="#">

ANASTAT

</a>
</div>