<?php if(isset($notification) && !empty($notification)) :?>
    <div class="alert alert-warning alert-dismissible anasatnotification" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <!-- <i class="ion-information-circled"></i> --> <?php echo $notification ?>
   </div>
<?php endif ?>

<?php if(session_has('notification')) :?>
    <div class="alert alert-warning alert-dismissible anasatnotification" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <!-- <i class="ion-information-circled anasatnotificationfont"></i> --> <?php echo session_get('notification') ?>
   </div>
<?php endif ?>