<div class="services-wrapper overviewdivbox">
    <h3><i class="ion-clipboard"></i> Overview</h3>

    <div class="row" id="requestlists">
        <!-- DATBASE OVERVIEW -->
        <div class="col-md-12 hide" id="databaseoverview">
        <h5 class="client-title site-init no-margin" style="">REQUEST DETAILS</h5>
            <h5 class="site-red font12">Database</h5>
            <span class="content site-init"></span>
            <hr class="splitter"/>
        </div>

        <!-- Table OVERVIEW -->
        <div class="col-md-12 hide" id="tableoverview">
            <h5 class="site-red font12">Table</h5>
            <span class="content site-init"></span>
            <hr class="splitter"/>
        </div>

        <!-- Level of Aggregation -->
        <div class="col-md-12 hide" id="lagoverview">
            <h5 class="site-red font12">Level Of Aggregation</h5>
            <span class="content site-init"></span>
            <hr class="splitter"/>
        </div>

        <!-- Cateory of Aggregation -->
        <div class="col-md-12 hide" id="cagoverview">
            <h5 class="site-red font12">Cateory Of Aggregation</h5>
            <span class="content site-init"></span>
            <hr class="splitter"/>
        </div>

        <!-- Variables -->
        <div class="col-md-12 hide" id="freqoverview">
            <h5 class="site-red font12">Frequency</h5>
            <span class="content site-init"></span>
            <hr class="splitter"/>
        </div>

        <!-- Variables -->
        <div class="col-md-12 hide" id="variableoverview">
            <h5 class="site-red font12">Variables</h5>
            <span class="content site-init"></span>
            <hr class="splitter"/>
        </div>

        <!-- Periods -->
        <div class="col-md-12 hide" id="periodoverview">
            <h5 class="site-red font12">Periods</h5>
            <span class="content site-init"></span>
            <hr class="splitter"/>
        </div>

        <!-- Note -->
        <div class="col-md-12 hide" id="commentoverview">
            <h5 class="site-red font12">Comment</h5>
            <span class="content site-init"></span>
            <!-- <hr class="splitter"/>> -->
        </div>

        <div id="savereview" class=" col-md-10 nopad hide">
            <a href="#" id="submitAll" class="btn button-custom btn-custom-two pull-right font12" onclick="Anastat.Request.SubmitAllRequest()">Submit All Requests</a>
        </div>