<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include($viewpath.'partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">

</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include($viewpath."partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<ol class="breadcrumb">
			<li><a href="<?php echo geturl('admin/dashboard')?>">Dashboard</a></li>
			<li><a href="<?php echo geturl("admin/database/{$database['id']}/tables")?>">Database</a></li>
			<li class="active">Assign-Tables</li>
	</ol>
	
		<hr>
		<div class="row font12">
		<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
		<?php endif ?>

		<!-- ADD NEW DATABASE -->
		<form class="form-horizontal" method="post" action="">
			<div class="col-md-10" id="logindiv">
				<input type="text" class="form-control disabled" disabled value="<?php echo $Database['databasename'] ?>" />
				<input type="hidden" name="database" value="<?php echo $Database['id'] ?>" />
			</div>

				
			<div class="col-md-10">
				<select name="tables[]" required multiple class="form-control chosentable aggtables" data-placeholder="Assign Tables">
					<?php foreach($Tables as $data) :?>
					<option value="<?php echo $data['id'] ?>"><?php echo $data['table_name'] ?></option>
					<?php endforeach ?>
				</select>
			</div>
			
			<div class="col-md-10 coverbd">
				<!-- SELECT ALL -->
					<div class="col-md-6">
						<div class="checkbox site-init font12">
							<label>
								<input type="checkbox" name="all" value="yes"> Select All Tables
							 </label>
						</div>
					</div>

					<div class="col-md-6 nopad">
						<div class="checkbox site-init font12">
							<label>
								<input type="checkbox" name="notall" value="yes"> Deselect All Tables
							 </label>
						</div>
					</div>
				<!-- END -->
			</div>

			<div id="submitdiv" class="col-md-12">
			<br>
				<button  class="btn button-custom btn-custom-two">Assign</button>
			</div>
		</form>
		<!-- END DATABASE -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER