<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->>

<!-- MENU SECTION -->
<?php include($viewpath.'partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include($viewpath."partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<h4 class="site-init inline">Tables</h4> 
	<a href="<?php echo geturl("admin/survey") ?>" class="site-init action-btn pull-right">
		<i class="ion-ios-arrow-back fonts site-red"></i> Go Back</a>
		<hr>
		<div class="row font12">
		<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
		<?php endif ?>

		<h5 class="site-init text-center">Add Free Survey Data</h5> 

		<!-- ADD NEW DATABASE -->
		<form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
			<div class="col-md-12" id="logindiv">
				<div class="col-md-10 nopad" id="pastetablediv">

					<input type="text" class="form-control" name="filename" required placeholder="Data name" 
					value="<?php echo isset($_POST['filename']) ? $_POST['filename'] : "" ?>"/>

						<select name="sector" required class="form-control">
						<option value="">Select Sub-Sector</option>
						<?php foreach($Sectors as $sector) :?>
						<option value="<?php echo $sector['id'] ?>"><?php echo $sector['name'] ?></option>
						<?php endforeach ?>
						</select>
				</div>
				
				<div class="col-md-5 nopad">
					<input type="file" class="form-control" name="file">
				</div>

				<div id="submitdiv" class="col-md-10">
				<button  class="btn button-custom btn-custom-two pull-right">Add Data</button>
				</div>

			</div>

		</form>
		<!-- END DATABASE -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/footer.phtml') ?>
<!-- END FOOTER