<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->
<!-- MENU SECTION -->
<?php include($viewpath.'partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include($viewpath."partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<h4 class="site-init inline">Request</h4> 
	<a href="<?php echo geturl("admin/requests") ?>" class="site-init action-btn pull-right">
		<i class="ion-ios-arrow-back fonts site-red"></i> Go Back</a>
		<hr>
		<div class="row font12">
		<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
		<?php endif ?>

			<?php if(!empty($Requests)) :?>

			<?php foreach($Requests as $key => $Request):?>
			
			<?php if($key == 0):?>
			<h5 class="text-center site-init">CLIENT DETAIL</h5>
			<hr>
			<div class="col-md-6 site-init">
			<div class="site-red col-md-2">Name</div>
			<div class="col-md-10"><?php echo strtoupper( $Request['name'] ) ?></div>
			</div>

			<div class="col-md-6 site-init">
			<div class="site-red col-md-2">Email</div>
			<div class="col-md-10"><?php echo strtoupper( $Request['email'] ) ?></div>
			</div>

			<div class="col-md-6 site-init">
			<div class="site-red col-md-2">Phone</div>
			<div class="col-md-10"><?php echo strtoupper( $Request['phone'] ) ?></div>
			</div>

			<div class="col-md-6 site-init">
			<div class="site-red col-md-3">Designation</div>
			<div class="col-md-9">
			<?php echo (null != $Request['position_instituition']) ?strtoupper($Request['position_instituition']) : "Not specified" ?>
			</div>
			</div>

			<div class="col-md-6 site-init">
			<div class="site-red col-md-2">Code</div>
			<div class="col-md-10"><?php echo (null != $Request['affiliate_code']) ?strtoupper($Request['affiliate_code']) : "Not specified" ?></div>
			</div>

			<div class="col-md-12 site-init">
			<div class="site-red col-md-1">Affiliate</div>
			<div class="col-md-10"><?php echo (null != $Request['affiliate_name']) ? strtoupper($Request['affiliate_name']) : "Not specified" ?></div>
			</div>
			<hr>
			
			<div class="row">
			<div class="col-md-12 site-init">
			<h5 class="text-center site-init">REQUESTS</h5>
			<hr>
			</div>
			</div>
			<?php endif ?>
			
			<div class="col-md-12">
			<h5 class="counter"><?php echo ($key + 1)?></h5>
			</div>

			<div class="col-md-12 site-init">
			<div class="site-red col-md-4">Database</div>
			<div class="col-md-8"><?php echo $Request['databasename'] ?></div>
			</div>

			<div class="col-md-12 site-init">
			<div class="site-red col-md-4">Level Of Aggregation</div>
			<div class="col-md-8"><?php echo $Request['level_aggregation'] ?></div>
			</div>
			
			<div class="col-md-12 site-init">
			<div class="site-red col-md-4">Category Of Aggregation</div>
			<div class="col-md-8"><?php echo implode(',',json_decode($Request['category_aggregation'],true)) ?></div>
			</div>

			<div class="col-md-12 site-init">
			<div class="site-red col-md-4">Frequency</div>
			<div class="col-md-8"><?php echo $Request['frequency'] ?></div>
			</div>

			<div class="col-md-12 site-init">
			<div class="site-red col-md-4">Variable</div>
			<div class="col-md-8"><?php echo implode(',',json_decode($Request['variable'],true)) ?></div>
			</div>

			<div class="col-md-12 site-init">
			<div class="site-red col-md-4">Period</div>
			<div class="col-md-8"><?php echo implode('&nbsp; - &nbsp;',json_decode($Request['period'],true)) ?></div>
			</div>
			
			<div class="col-md-12 site-init">
				<div class="site-red col-md-4">Approved By Affiliate</div>
				<div class="col-md-8"><?php echo  $Request['approved'] ?></div>
			</div>
			
			<div class="col-md-12 site-init">
			<div class="site-red col-md-4">Status</div>
			<div class="col-md-3"><?php echo ($Request['status'] == 1) ? "Treated <i class='ion-ios-checkmark-outline fonts green'></i>"
																		  : "Not Treated <i class='ion-ios-close-outline fonts site-red'></i>" ?></div>
			<div class="col-md-5">
			<form class="form-inline" method="GET" action="<?php echo geturl('admin/requests') ?>">
			  <div class="form-group">
			  <input type="hidden" name="for" value="status" />
			  <input type="hidden" name="id" value="<?php echo $Request['id'] ?>" />
			    <select class="requeststatus" name="status">
			    	<option value="">Change Status</option>
			    	<option value="1">Treated</option>
			    	<option value="0">Not Treated</option>
			    </select>
			  </div>
			 </form>
			</div>

			</div>

			<div class="col-md-12 site-init">
			<div class="site-red col-md-4">Time Requested</div>
			<div class="col-md-8"><?php echo date_create($Request['created_at'])->format('d M Y  h:i:s') ?></div>
			</div>

			<div class="col-md-12">
			<hr class="split-list">
			</div>

			<?php endforeach ?>
			<?php else :?>
			<div class="notify">Requests Not Found!</div>
			<?php endif ?>
				
		</div>
		<!-- END Databases -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/footer.phtml') ?>
<!-- END FOOTER