<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include($viewpath.'partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include($viewpath."partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<ol class="breadcrumb">
		<li><a href="<?php echo geturl('admin/dashboard')?>">Dashboard</a></li>
		<li><a href="<?php echo geturl('admin/dashboard')?>">Table</a></li>
		<li class="active">Add New</li>
	</ol>
	
		<hr>
		<div class="row font12">
		<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
		<?php endif ?>

		<!-- ADD NEW DATABASE -->
		<form class="form-horizontal" method="post" action="">
			<div class="col-md-12" id="logindiv">
				<div class="col-md-12 nopad" id="pastetablediv">
				<div class="col-md-12 nopad" id="copytablediv">
					<div class="col-md-8 nopad" id="tablesbox">
						<input type="text" class="form-control" name="tables[]" required placeholder="Table Name"/>
					</div>

					<div class="col-md-2 col-md-offset-1 nopad" id="tablesbox">
						<input type="text" class="form-control" name="codes[]" required placeholder="Code"/>
					</div>

					<div class="col-md-1">
					<span class="ion-android-add-circle site-red dombutton" title="More" onclick="Anastat.Mixing.CloneDOM('copytablediv','pastetablediv',true)">
					</span>
					</div>
				</div>
				</div>
			</div>

			<div id="submitdiv" class="col-md-12">
				<button  class="btn button-custom btn-custom-two">Add</button>
			</div>
		</form>
		<!-- END DATABASE -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER