<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->
<!-- MENU SECTION -->
<?php include($viewpath.'partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include($viewpath."partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<ol class="breadcrumb">
		<li><a href="<?php echo geturl('admin/dashboard')?>">Dashboard</a></li>
		<li><a href="<?php echo geturl('admin/dashboard')?>">Table</a></li>
		<li class="active">Edit</li>
	</ol>

		<hr>
		<div class="row font12">
		<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
		<?php endif ?>

		<!-- EDIT TABLE -->
		<form class="form-horizontal" method="post" action="">
			<div class="col-md-8" id="logindiv">
				<input type="hidden" name="table_id" value="<?php echo $Table['id'] ?>">
				<input type="text" class="form-control" name="table" value="<?php echo $Table['table_name'] ?>" required 
				placeholder="Table Name"/>
			</div>
			
			<div class="col-md-2 col-md-offset-1" id="logindiv">
				<input type="text" class="form-control" name="code" value="<?php echo $Table['code'] ?>" required placeholder="Code"/>
			</div>

			<div id="submitdiv" class="col-md-12">
				<button  class="btn button-custom btn-custom-two">Update</button>
			</div>
		</form>
		<!-- END -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/footer.phtml') ?>
<!-- END FOOTER