<?php
$viewpath = config('view_path');
@include($viewpath.'partials/header.phtml')
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php @include($viewpath.'partials/frontmenu.phtml') ?>
<!--MENU SECTION END-->

<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">

<div class="col-xs-12 col-sm-12 text-center">
	<h2 class="site-red no-margin">Page Not Found!</h2>
	<hr class="site-red" style="margin-top:15px;margin-bottom:50px;width:5%"/>
</div>

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">

</div>

<div class="col-xs-12 col-sm-12">
	<div class="services-wrapper">
	<h1 class="text-center"><i class="ion-sad"></i></h1>
	<!-- <h4 class="text-center" style="color:grey">Page Not Found</h4> -->
	<h4 class="text-center site-red">We are sorry but we need you to turn on your javascript from your browser to enable you use our service. <br><!-- <a href="#">You are seeing this message because you probably turned off your javascript</a> --> </h4>
	</div>
</div>

<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
	
</div>


</div>
</div>
</section>


<!-- FOOTER -->
<?php @include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER