<?php
$viewpath = config('view_path');
include($viewpath.'/partials/header.phtml');
?>
<!-- END HEADER -->

<br>
<br>
<section id="services" style="padding-bottom: 20%;">
<div class="container">
<div class="row text-center header">
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	
</div>

<div class="col-xs-12 col-sm-12 col-md-5 col-lg-5">
	<div class="services-wrapper">
	<?php include($viewpath.'partials/notification.phtml') ?>
	<h5 class="site-init"><i class="ion-ios-barcode-outline site-red"></i>PROVIDE REQUEST SUBMISSION CODE</h5>
		
		<form class="form-horizontal" method="post" action="">
			<div class="row" id="">

				<div class="col-md-12" id="logindiv">
					<input type="text" name="code" class="form-control min-field" autocomplete="off" required placeholder="code e.g 92345678906" 
					value="<?php echo get('code') ?>" />
				</div>

				<div id="submitdiv" class="col-md-12">
						<button  class="btn button-custom btn-custom-two pull-right">
						Check <i class="ion-ios-eye-outline fonts white"></i>
						</button>
				</div>

			</div>
		</form>
		<br>
		<br>
	</div>
		
</div>

<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
</div>


</div>
</div>
</section>



<!--CONTACT SECTION START-->

<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php include($viewpath.'/partials/footer.phtml') ?>
<!-- END FOOTER