<?php
$viewpath = config('view_path');
@include($viewpath.'partials/header.phtml')
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php @include($viewpath.'partials/frontmenu.phtml') ?>
<!--MENU SECTION END-->

<!--SERVICE SECTION START-->

<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<section id="services" style="padding-top:55px">
<div class="container">
<div class="row text-center header margin-top-4">
<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 class="" style="color:#444;font-size:18px">REQUEST DATA OVERVIEW</h3>
</div>
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
<div class="services-wrapper">
	<div class="row bioform" id="requestlists">
		<h5 class="client-title site-init no-margin" style="">BIO FORM</h5>
		<div class="col-md-12" id="databaseoverview">
			<h5 class="site-red">Name</h5>
			<span class="content site-init"><?php echo $Client['name'] ?></span>
			<hr class="splitter"/>
		</div>
		<div class="col-md-12" id="databaseoverview">
			<h5 class="site-red">Sex</h5>
			<span class="content site-init"><?php echo $Client['sex'] ?></span>
			<hr class="splitter"/>
		</div>
		<div class="col-md-12" id="databaseoverview">
			<h5 class="site-red">Email</h5>
			<span class="content site-init"><?php echo $Client['email'] ?></span>
			<hr class="splitter"/>
		</div>
		<div class="col-md-12" id="databaseoverview">
			<h5 class="site-red">Phone</h5>
			<span class="content site-init"><?php echo $Client['phone'] ?></span>
			<hr class="splitter"/>
		</div>
		<div class="col-md-12" id="databaseoverview">
			<h5 class="site-red">Address</h5>
			<span class="content site-init"><?php echo $Client['address'] ?></span>
			<hr class="splitter"/>
		</div>
		<?php if($Client['affiliate_id'] != 0 || $Client['affiliate_id'] != null):?>
		<div class="col-md-12" id="databaseoverview">
			<h5 class="site-red">Designation</h5>
			<span class="content site-init"><?php echo $Client['position_instituition'] ?></span>
			<hr class="splitter"/>
		</div>
		<div class="col-md-12" id="databaseoverview">
			<h5 class="site-red">Identification No</h5>
			<span class="content site-init"><?php echo $Client['identification_no'] ?></span>
		</div>
		<?php endif ?>

        <div class="col-md-12" id="databaseoverview">
            <br>
            <h5 class="client-title site-init no-margin" style="">Request Code</h5>
            <h6 class="content site-init text-center bold"><?php echo $Client['transaction_id'] ?></h6>
            <hr class="splitter"/>
        </div>


    </div>
</div>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
	<div class="services-wrapper">
	<div class="row">
				

				<?php foreach($Requests as $key => $request): ?>
				<div class="row" id="requestlists">
				<h5 class="client-title site-init no-margin" style="">REQUEST <?php echo $key + 1 ?></h5>
				<!-- DATBASE OVERVIEW -->
				<div class="col-md-6" id="">
					<h5 class="site-red">Database</h5>
					<span class="content site-init"><?php echo $request['databasename'] ?></span>
				<hr class="splitter"/>
				</div>

				<!-- Table OVERVIEW -->
				<div class="col-md-6" id="">
					<h5 class="site-red">Table</h5>
					<span class="content site-init"><?php echo $request['datatable'] ?></span>
				<hr class="splitter"/>
				</div>

				<!-- Level of Aggregation -->
				<div class="col-md-6" id="">
					<h5 class="site-red">Level Of Aggregation</h5>
					<span class="content site-init"><?php echo $request['level_aggregation'] ?></span>
				<hr class="splitter"/>
				</div>

				<!-- Cateory of Aggregation -->
				<div class="col-md-6" id="">
					<h5 class="site-red">Cateory Of Aggregation</h5>
					<span class="content site-init"><?php echo implode(",", json_decode($request['category_aggregation'],true) ) ?></span>
				<hr class="splitter"/>
				</div>
			
				<!-- Variables -->
				<div class="col-md-12" id="">
					<h5 class="site-red">Frequency</h5>
					<span class="content site-init"><?php echo $request['frequency'] ?></span>
				<hr class="splitter"/>
				</div>

				<!-- Variables -->
				<div class="col-md-12" id="">
					<h5 class="site-red">Variables</h5>
					<span class="content site-init">
					<?php echo wordwrap( strtoupper( implode(",", json_decode($request['variable'],true) ) ),100,"<br />\n" ) ?></span>
				<hr class="splitter"/>
				</div>

				<!-- Periods -->
				<div class="col-md-12" id="">
					<h5 class="site-red">Periods</h5>
					<span class="content site-init"><?php echo implode("&nbsp; , &nbsp;", json_decode($request['period'],true) ) ?></span>
				<hr class="splitter"/>
				</div>

				<!-- Note -->
				<div class="col-md-6" id="">
					<h5 class="site-red">Comment</h5>
					<span class="content site-init"><?php echo empty($request['comment']) ? 'No comment' : $request['comment'] ?></span>
				</div>

				<div class="col-md-6" id="">
					<h5 class="site-red">Time Requested</h5>
					<span class="content site-init"><?php echo date_create($request['created_at'])->format('d M Y  h:i:s') ?></span>
				</div>
			</div>
			<?php endforeach ?>
	</div>

	</div>

</div>


</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER