<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include($viewpath.'/partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
    <div class="container">
        <div class="row text-center header">

        </div>
        <div class="row animate-in" data-anim-type="fade-in-up">

            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <?php include($viewpath."partials/adminmenu.phtml") ?>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
                <div class="services-wrapper">
                    <ol class="breadcrumb">
                        <li><a href="<?php echo geturl('admin/dashboard')?>">Dashboard</a></li>
                        <li><a href="<?php echo geturl('admin/affiliate')?>">Affiliate</a></li>
                        <li class="active">Edit</li>
                    </ol>

                    <hr>
                    <div class="row">
                        <?php include($viewpath.'partials/notification.phtml') ?>

                        <!-- ADD NEW AFFILIATES -->
                        <form class="form-horizontal" method="post" action="">
                            <div class="col-md-12"><h4 class="">General Details</h4></div>
                            <input type="hidden" name="id" value="<?php echo $Affiliate['id'] ?>" />
                            <div class="col-md-12" id="logindiv">
                                <input type="text" class="form-control" name="affiliate" required value="<?php echo $Affiliate['affiliate_name'] ?>" placeholder="Affiliate name"/>
                            </div>

                            <div class="col-md-3" id="logindiv">
                                <select class="chosentable" required name="type">
                                    <option value="">Choose Type</option>
                                    <option <?php echo ($Affiliate['affiliate_type'] == "paid subscription") ? "selected" : "" ?> value="paid subscription">Paid Subscription</option>
                                    <option <?php echo ($Affiliate['affiliate_type'] == "free trial") ? "selected" : "" ?> value="free trial">Free Trial</option>
                                </select>
                            </div>

                            <div class="col-md-3" id="logindiv">
                                <input type="text" class="form-control" name="code" required value="<?php echo $Affiliate['affiliate_code'] ?>" placeholder="Affiliate code"/>
                            </div>

                            <div class="col-md-6" id="logindiv">
                                <input type="email" class="form-control" name="email" required value="<?php echo $Affiliate['affiliate_email'] ?>" placeholder="Affiliate email"/>
                            </div>

                            <div class="col-md-12"><h4 class="">Subscription</h4></div>
                            <div class="col-md-6" id="logindiv">
                                <select class="chosentable" <?php echo !empty($Active) ? "disabled" : " name='subscription' " ?>>
                                    <option value="">Choose Plan</option>
                                    <?php foreach($Subscriptions as $data) :?>
                                        <option <?php echo ($data['id'] == $Active['plan_id']) ? "selected" : "" ?>  value="<?php echo $data['id']?>"><?php echo $data['name'] ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>


                            <div id="submitdiv" class="col-md-6">
                                <button  class="btn button-custom btn-custom-two pull-right">Update</button>
                            </div>
                        </form>
                        <!-- END AFFILIATES -->

                    </div>
                </div>



            </div>
        </div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include($viewpath.'/partials/footer.phtml') ?>
<!-- END FOOTER