<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include($viewpath.'partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include($viewpath."partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<ol class="breadcrumb">
		<li><a href="<?php echo geturl('admin/dashboard')?>">Dashboard</a></li>
		<li><a href="<?php echo geturl("admin/affiliate/{$id}/view")?>">Affiliate</a></li>
		<li class="active">User</li>
	</ol>
	
	<?php if(empty($User)): ?>
	<a href="<?php echo geturl("admin/affiliate/{$id}/adduser") ?>" class="site-init action-btn pull-right 
	<?php echo (user('auth') == FALSE) ? "disabled" : "" ?>">

	<i class="ion-plus fonts site-red"></i>Add New</a>
	<?php endif ?>

		<hr>
		<div class="row dash-row">
			
			<?php include($viewpath.'partials/notification.phtml') ?>

			<!-- START AFFILIATES -->
			<div class="col-md-2 nopad site-red">
			Username
			</div>
			<div class="col-md-2 site-red">
			Type
			</div>
			<div class="col-md-3 site-red">
			Last Login
			</div>
			<div class="col-md-3 site-red">
			Added On
			</div>

			<div class="col-md-2 site-red">
			Actions
			</div>
			<hr>
			
			<?php if(!empty($User)) :?>

			<div class="col-md-2 nopad site-init">
			<?php echo ($User['username']) ?>
			</div>

			<div class="col-md-2 site-init">
			<?php echo ($User['type']) ?>
			</div>

			<div class="col-md-3 site-init">
			<?php echo date_create($User['last_login'])->format('d M Y h:i:s A') ?>
			</div>

			<div class="col-md-3 site-init">
			<?php echo  date_create($User['created_at'])->format('d M Y h:i:s A') ?>
			</div>

			<div class="col-md-2">
			<?php if($User['role'] != 1): ?>
			<a title="delete"  href="#" onclick="Anastat.Mixing.AdminPromptDelete('<?php echo geturl("admin/affiliate/{$id}/dropuser") ?>')" class="site-init action-btn">
			<i class="ion-ios-trash fonts site-red"></i>
			</a>
			<?php endif ?>
			<a title="edit"  href="<?php echo geturl("admin/affiliate/{$id}/edituser") ?>" class="site-init action-btn">
			<i class="ion-edit fonts site-red"></i>
			</a>
			</div>

			<div class="col-md-12">
			<hr class="split-list">
			</div>

			<?php else :?>
			<div class="notify">No Manager Registered For This Affiliate!</div>
			<?php endif ?>

		</div>
		<!-- END AFFILIATES -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER