<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include($viewpath.'partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
    <div class="container">
        <div class="row text-center header">
            <!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
            <h3 style="margin:0px;">REQUEST DATA</h3>
            <hr style="margin-top:5px !mportant;margin-bottom:0px"/>
            </div> -->
        </div>
        <div class="row animate-in" data-anim-type="fade-in-up">

            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <?php include($viewpath."partials/adminmenu.phtml") ?>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
                <div class="services-wrapper">
                    <ol class="breadcrumb">
                        <li><a href="<?php echo geturl('admin/dashboard')?>">Dashboard</a></li>
                        <li><a href="<?php echo geturl('admin/affiliate')?>">Affiliate</a></li>
                        <li class="active">View</li>
                    </ol>
                    <hr>

                    <div class="row dash-row">
                        <div class="col-md-8">
                            <h4>General Details</h4>
                            <hr>
                            <div class="col-md-12 nopad">
                            <h6 class="site-init"><b class="site-red">Affiliate Name</b> :
                                <?php echo ucfirst($Affiliate['affiliate_name']) ?>
                            </h6>
                            </div>
                            <div class="col-md-12 nopad">
                            <h6 class="site-init"><b class="site-red">Email</b> :
                                <?php echo strtolower($Affiliate['affiliate_email']) ?>
                            </h6>
                            </div>
                            <div class="col-md-12 nopad">
                                <h6 class="site-init"><b class="site-red">Type</b> :
                                    <?php echo ucfirst($Affiliate['affiliate_type']) ?>
                                </h6>
                            </div>
                            <div class="col-md-12 nopad">
                                <h6 class="site-init"><b class="site-red">Code</b> :
                                    <?php echo $Affiliate['affiliate_code'] ?>
                                </h6>
                            </div>
                            <div class="col-md-12 nopad">
                                <h6 class="site-init"><b class="site-red">Joined</b> :
                                    <?php echo format_date($Affiliate['created_at'],'d M Y') ?>
                                </h6>
                            </div>

                            <div class="col-md-12 nopad">
                                <br>
                                <br>
                                <h4>Actions</h4>
                                <hr>
                                <a class="btn button-custom btn-custom-two" href="<?php echo geturl("admin/affiliate/{$Affiliate['id']}/edit") ?>" title="Edit Affiliate">
                                    <i class="ion-edit fonts white"></i> Edit
                                </a>
                                <a class="btn button-custom btn-custom-two" href="#" onclick="Anastat.Mixing.AdminPromptDelete('<?php echo geturl("admin/affiliate/{$Affiliate['id']}/drop") ?>')" title="Delete Affiliate">
                                    <i class="ion-trash-a fonts white"></i> Delete
                                </a>
                                <a class="btn button-custom btn-custom-two" href="<?php echo geturl("admin/affiliate/{$Affiliate['id']}/user") ?>">
                                    <i class="ion-key fonts white"></i>Manage User
                                </a>
                                <a class="btn button-custom btn-custom-two" href="<?php echo geturl('admin/affiliate?for=report&id='.$Affiliate['id']) ?>">
                                    <i class="ion-connection-bars fonts white"></i> Report
                                </a>
                                <br>
                                <a class="btn button-custom btn-custom-two" href="<?php echo geturl("admin/requests/{$Affiliate['id']}/affiliate") ?>">
                                    <i class="ion-clipboard fonts white"></i>View Clients Requests
                                </a>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="col-md-12 no-pad">
                                <h4>Active Plan</h4>
                                <hr>
                                <?php if(empty($Active)):?>
                                    <h6 class="site-init">No Active Plan!</h6>
                                    <form class="form-horizontal" action="" method="POST">
                                        <div class="col-md-12 nopad" id="logindiv">
                                            <input type="hidden" name="affiliate" value="<?php echo $Affiliate['id'] ?>" />
                                            <select class="chosentable"  name="plan" required>
                                                <option value="">Choose Plan</option>
                                                <?php foreach($Subscriptions as $data) :?>
                                                    <option value="<?php echo $data['id']?>"><?php echo $data['name'] ?></option>
                                                <?php endforeach ?>
                                            </select>
                                        </div>
                                        <div id="submitdiv" class="col-md-12 nopad">
                                            <button  class="btn btn-sm button-custom btn-custom-two pull-right">Subscribe</button>
                                        </div>
                                    </form>
                                <?php else :?>
                                    <h6 class="site-init"><b class="site-red">Subscribed</b> : <?php echo format_date($Active['created_at'],'d M Y') ?></h6>
                                    <h6 class="site-init"><b class="site-red">Expiry Date</b> : <?php echo format_date($Active['expires'],'d M Y') ?></h6>
                                    <h6 class="site-init"><b class="site-red">Plan Name</b> : <?php echo $Active['name'] ?></h6>
                                    <h6 class="site-init"><b class="site-red">Data-Size</b> :      <?php echo $Active['datasize'] ?>(kb)</h6>
                                <?php endif ?>
                            </div>
                            <div class="col-md-12 no-pad">
                                <br>
                                <br>
                                <br>
                                <br>
                                <br>
                                <h4>Plan History </h4>
                                <hr>
                                <?php if(!empty($History)): ?>
                                <?php foreach($History as $plan) :?>
                                <h6 class="site-init"><b class="site-red">Plan Name</b> : <?php echo $plan['name'] ?></h6>
                                <h6 class="site-init"><b class="site-red">Data-Size</b> : <?php echo $plan['datasize'] ?>(kb)</h6>
                                <h6 class="site-init"><b class="site-red">Expired</b> : <?php echo format_date($plan['expires'],'d M Y') ?></h6>
                                <hr>
                                <?php endforeach ?>
                                <?php else: ?>
                                    <h6 class="site-init">History Empty!</h6>
                                <?php endif ?>
                            </div>
                        </div>

                    </div>

                </div>
            </div>



        </div>
    </div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER