<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include($viewpath.'partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include($viewpath."partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
	<div class="services-wrapper">
		<h4 class="site-init">Dashboard</h4>
		<hr>
		<?php include($viewpath.'partials/notification.phtml') ?>

		<!--ANASTAT STAT-->
		<div class="col-md-4 col-sm-8 col-lg-4 margin-top-1 col-md-offset-1 col-lg-offset-1 dashboardstat">
            <div class="col-md-6 nopad">
                <h3 class="site-init text-left" id="count">10</h3>
            </div>
            <div class="col-md-6">
                    <span class="ion-ios-people pull-right iconstat"></span>
            </div>
            <div class="col-md-12 nopad">
                <h6 class="text-center site-init captionstat">NEW AFFILIATED REQUESTS</h6>
            </div>
		</div>

		<div class="col-md-4 col-sm-8 col-lg-4 margin-top-1 col-md-offset-1 col-lg-offset-1 dashboardstat">
            <div class="col-md-6 nopad">
                <h3 class="site-init text-left" id="count">06</h3>
            </div>
            <div class="col-md-6">
                <span class="ion-android-done-all pull-right iconstat"></span>
            </div>
            <div class="col-md-12 nopad">
                <h6 class="text-center site-init captionstat">APPROVED AFFILIATED REQUESTS</h6>
            </div>
		</div>

		<div class="col-md-4 col-sm-8 col-lg-4 margin-top-1 col-md-offset-1 col-lg-offset-1 dashboardstat">
            <div class="col-md-6 nopad">
                <h3 class="site-init text-left" id="count">105</h3>
            </div>
            <div class="col-md-6">
                <span class="ion-ios-personadd pull-right iconstat"></span>
            </div>
            <div class="col-md-12 nopad">
                <h6 class="text-center site-init captionstat">NEW INDEPENDENT REQUESTS</h6>
            </div>
		</div>

		<div class="col-md-4 col-sm-8 col-lg-4 col-md-offset-1 col-lg-offset-1 margin-top-1 dashboardstat">
            <div class="col-md-6 nopad">
                <h3 class="site-init text-left" id="count">10</h3>
            </div>
            <div class="col-md-6">
                <span class="ion-cash pull-right iconstat"></span>
            </div>
            <div class="col-md-12 nopad">
                <h6 class="text-center site-init captionstat">PAID INDEPENDENT REQUESTS</h6>
            </div>
		</div>

		<div class="col-md-4 col-sm-8 col-lg-4 margin-top-1 col-md-offset-1 col-lg-offset-1 dashboardstat">
            <div class="col-md-12 text-center">
                <span class="ion-ios-cloud-download-outline iconstat"></span>
                <br>
            </div>
            <div class="col-md-12 nopad">
                <h6 class="text-center site-init captionstat">DOWNLOAD REPORTS</h6>
            </div>
		</div>
		<!--END-->

	</div>
	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER