<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include($viewpath.'partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">

</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include($viewpath."partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<ol class="breadcrumb">
			<li><a href="<?php echo geturl('admin/dashboard')?>">Dashboard</a></li>
			<li><a href="<?php echo geturl('admin/survey')?>">Survey</a></li>
			<li><a href="<?php echo geturl('admin/sector')?>">Sector</a></li>
			<li class="active">Edit</li>
	</ol> 
		<hr>
		<div class="row font12">

		<!-- ADD NEW DATABASE -->
		<form class="form-horizontal" method="post" action="">
			<div class="col-md-12" id="logindiv">
				<div class="col-md-8 nopad" id="pastetablediv">
					<input type="hidden" name="id" value="<?php echo $Sector['id'] ?>" />
					<input type="text" class="form-control" name="name" required placeholder="Sector name" 
					value="<?php echo $Sector['name'] ?>"/>
				</div>
				
				<div id="submitdiv" class="col-md-4">
				<button  class="btn button-custom btn-custom-two font12 no-margin">Update</button>
				</div>

			</div>

		</form>
		<!-- END DATABASE -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER