<!--HEADER -->
<?php include('partials/adminheader.phtml') ?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include('partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include("partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<h4 class="site-init inline">Users</h4> 
	<a href="<?php echo geturl("admin/affiliate") ?>" class="site-init action-btn pull-right">
		<i class="ion-ios-arrow-back fonts site-red"></i> Go Back</a>
		<hr>
		<div class="row font12">
		<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
		<?php endif ?>

		<h5 class="site-init text-center">Add New Affiliate Manager</h5> 

		<!-- ADD NEW DATABASE -->
		<form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
			<div class="col-md-12" id="logindiv">
				<div class="col-md-10 nopad" id="pastetablediv">
					<input type="email" class="form-control" name="username" required placeholder="Username" value="<?php echo isset($_POST['username']) ? $_POST['username'] : "" ?>"/>

					<input type="password" class="form-control" name="password" required  placeholder="Password"/>

					<input type="password" class="form-control no-margin" name="password_confirm" required  id="passwordcheck" 
					placeholder="Confirm password"/>
					
					<small id="passwordmatch" class="site-init codeinfo"></small>

						<select class="form-control" name="affiliateid">
						<?php foreach($Affiliates as $affiliate) :?>
						<option <?php echo ($affiliate['id'] == $affiliateid) ? 'selected' : '' ?> value="<?php echo $affiliate['id']?>">
						<?php echo $affiliate['affiliate_name'] ?>
						</option>
						<?php endforeach ?>
						</select>
				</div>
				
				<div id="submitdiv" class="col-md-10">
				<button  class="btn button-custom btn-custom-two pull-right">Add Manager</button>
				</div>

			</div>

		</form>
		<!-- END DATABASE -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/adminfooter.phtml') ?>
<!-- END FOOTER