<!--HEADER -->
<?php include('partials/adminheader.phtml') ?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include('partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include("partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<h4 class="site-init inline">Database</h4>
	<a href="<?php echo geturl("admin/database") ?>" class="site-init action-btn pull-right">
		<i class="ion-ios-arrow-back fonts site-red"></i> Go Back</a> 
		<hr>
		<div class="row">
		<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
		<?php endif ?>

		<h5 class="site-init text-center">Add New Database</h5> 

		<!-- ADD NEW DATABASE -->
		<form class="form-horizontal" method="post" action="">
			<div class="col-md-12 editor" id="logindiv">
				<input type="text" class="form-control" name="database" required placeholder="Database Name"/>

				<input type="text" class="form-control" name="code" required placeholder="Database Code"/>

				<select name="type" required class="form-control">
					<option value="">Select Database Type</option>
					<option value="micro">Micro</option>
					<option value="micro">Macro</option>
				</select>

				<h4 class="site-init text-center"><span class="ion-ios-help-outline site-init"></span> Database Help Content</h4>
				<textarea name="help" class="database_help form-control"></textarea>
			</div>

			<div id="submitdiv" class="col-md-12">
				<button  class="btn button-custom btn-custom-two pull-right">Add New Database</button>
			</div>
		</form>
		<!-- END DATABASE -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/adminfooter.phtml') ?>
<!-- END FOOTER