<!--HEADER -->
<?php include('partials/adminheader.phtml') ?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include('partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include("partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<h4 class="site-init inline">Affiliate</h4> 
	<a href="<?php echo geturl("admin/addaffiliate") ?>" class="site-init action-btn pull-right"><i class="ion-plus fonts site-red"></i> Add New Affiliate</a>
		<hr>
		<div class="row dash-row">
			
			<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
			<?php endif ?>

			<!-- START AFFILIATES -->
			<div class="col-md-1 site-red">
			S/N
			</div>
			<div class="col-md-5 site-red">
			Name
			</div>
			<div class="col-md-2 site-red">
			Affiliate Code
			</div>
			<div class="col-md-4 site-red">
			Actions
			</div>
			<hr>
			
			<?php if(!empty($Affiliates)) :?>
			<?php foreach($Affiliates as $key => $affiliate) :?>
			<div class="col-md-1 site-init">
			<?php echo $key + 1 ?>
			</div>

			<div class="col-md-5 site-init">
			<?php echo strtoupper($affiliate['affiliate_name']) ?>
			</div>

			<div class="col-md-2 site-init">
			<?php echo strtoupper($affiliate['affiliate_code']) ?>
			</div>

			<div class="col-md-4">
			<a title="delete" href="#" onclick='deletePromptAdmin("<?php echo geturl('admin/affiliate?action=drop&id='.$affiliate['id'] ) ?>")' class="site-init action-btn">
			<i class="ion-ios-trash fonts site-red"></i>
			</a>
			<a title="edit"  href="<?php echo geturl('admin/editaffiliate?id='.$affiliate['id'] ) ?>" class="site-init action-btn">
			<i class="ion-edit fonts site-red"></i>
			</a>
			<a title="view clients that has made request under this instituition"  
			href="<?php echo geturl('admin/clients?for=affiliate&id='.$affiliate['id'] ) ?>" 
			class="site-init action-btn"><i class="ion-person-stalker fonts site-red"></i>
			</a>
			<a title="Manage affiliate login" href="<?php echo geturl('admin/addaffiliateduser?affiliateid='.$affiliate['id']) ?>"
			 class="site-init action-btn"><i class="ion-android-person fonts site-red"></i>
			 </a>
			 <a title="Download Report" href="<?php echo geturl('admin/affiliate?for=report&id='.$affiliate['id']) ?>"
			 class="site-init action-btn"><i class="ion-connection-bars fonts site-red"></i>
			 </a>
			</div>
			
			<div class="col-md-12">
			<hr class="split-list">
			</div>

			<?php endforeach ?>
			<?php else :?>
			<div class="notify">Affiliate List Empty!</div>
			<?php endif ?>

		</div>
		<!-- END AFFILIATES -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/adminfooter.phtml') ?>
<!-- END FOOTER