<select data-placeholder="Select Category Of Aggregation..." class="chosentable dcaggregation" multiple tabindex="3"  required name="caggregation[]">
	<option value=""></option>
	<?php if(count($Caggregation) > 0) :?>
	<?php foreach($Caggregation as $aggregation) :?> 
	<option data-id="<?php echo $aggregation['id'] ?>" value="<?php echo $aggregation['code'] ?>">
	<?php echo $aggregation['category_aggregation_name'] ?></option>
	<?php endforeach ?>
	<?php else :?>
		<option value="">No results returned!</option>
	<?php endif ?>
</select>

<div class="col-md-6">
	<div class="checkbox site-init font12">
		<label>
			<input type="checkbox" name="selectallcat" value="yes"> Click to select all Categories
		 </label>
	</div>
</div>

<div class="col-md-6 nopad">
	<div class="checkbox site-init font12">
		<label>
			<input type="checkbox" name="deselectallcat" value="yes"> Click to deselect all Categories
		 </label>
	</div>
</div>