<!--HEADER -->
<?php include('partials/adminheader.phtml') ?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include('partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include("partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<h4 class="site-init inline">Requests</h4> 
		<hr>
		<div class="row dash-row">
			
			<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
			<?php endif ?>

			<!-- START Databases -->
			<div class="col-md-1 site-red">
			S/N
			</div>
			<div class="col-md-4 site-red">
			Client Name
			</div>

			<div class="col-md-4 site-red">
			Insituition
			</div>

			<div class="col-md-3 site-red">
			Actions
			</div>
			<hr>
			
			<?php if(!empty($Clients)) :?>
			<?php foreach($Clients as $key => $client) :?>
			<div class="col-md-1 site-init">
			<?php echo $key + 1 ?>
			</div>

			<div class="col-md-4 site-init">
			<?php echo strtoupper( $client['name'] ) ?>
			</div>

			<div class="col-md-4 site-init">
			<?php echo !empty($client['affiliate_name']) ? $client['affiliate_name'] : "Not Specified" ?>
			</div>

			<div class="col-md-3">
			<a title="Delete client &amp; requests" href="#" 
			onclick='deletePromptAdmin("<?php echo geturl('admin/clients?action=drop&id='.$client['id'] ) ?>")' 
			class="site-init action-btn">
			<i class="ion-ios-trash fonts site-red"></i></a>
			<a title="view client &amp; requests" href="<?php echo geturl('admin/requests?for=client&id='.$client['id'] ) ?>
			"class="site-init action-btn"><i class="ion-eye fonts site-red"></i></a>
			</div>

			<div class="col-md-12">
			<hr class="split-list">
			</div>

			<?php endforeach ?>
			<?php else :?>
			<div class="notify">Client List Empty!</div>
			<?php endif ?>

		</div>
		<!-- END Databases -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/adminfooter.phtml') ?>
<!-- END FOOTER