<!--HEADER -->
<?php include('partials/adminheader.phtml') ?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include('partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include("partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
	<div class="services-wrapper">
		<h4 class="site-init">Dashboard</h4>
		<hr>
		<?php// if(session_has('message')) :?>
			<!-- <div class="notify"><?php //echo session_get('message') ?></div> -->
		<?php //endif ?>
		
		<div class="row overview-dashboard">

			<div class="col-md-3 col-lg-3 col-sm-5 text-center modules">

			<i class="ion-briefcase"></i>
			<div class="col-md-12 nopad">
				<div class="col-md-6">
					<h5 class="site-init no-margin">Affiliates</h5>
				</div>
				<div class="col-md-6">
					<h5 class="site-red no-margin"><?php echo $Affiliates ?></h5>
				</div>
			</div>
			
			</div>

			<div class="col-md-3 col-lg-3 col-sm-5 text-center modules">

			<i class="ion-android-people"></i>
			<div class="col-md-12 nopad">
				<div class="col-md-6">
					<h5 class="site-init no-margin">Clients</h5>
				</div>
				<div class="col-md-6">
					<h5 class="site-red no-margin"><?php echo $Clients ?></h5>
				</div>
			</div>

			</div>

			<div class="col-md-3 col-lg-3 col-sm-5 text-center modules">
				<i class="ion-clipboard"></i>
				<div class="col-md-12 nopad">
					<div class="col-md-6">
						<h5 class="site-init no-margin">Requests</h5>
					</div>
					<div class="col-md-6">
						<h5 class="site-red no-margin"><?php echo $Requests ?></h5>
					</div>
				</div>
			</div>

			<div class="col-md-3 col-lg-3 col-sm-5 text-center modules">
				<i class="ion-connection-bars"></i>
				<h5 class="site-init no-margin"><a href="<?php echo geturl('admin/report') ?>" class="">Download Report</a></h5>
			</div>

		</div>
		
		<div class="row">
		<div class="col-md-12 nopad">
			<br>
				<small class="site-init codeinfo">
				<i class="fonts ion-information-circled site-red"></i>
				Visit <a href="<?php echo geturl('admin/affiliate') ?>" class="">Affiliates</a> 
				to download report for a particular affiliate
 				</small>
		</div>
		</div>
		
	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/adminfooter.phtml') ?>
<!-- END FOOTER