<!--HEADER -->
<?php include('partials/adminheader.phtml') ?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include('partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include("partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<h4 class="site-init inline">Databases</h4> 
	<a href="<?php echo "addatabase" ?>" class="site-init action-btn pull-right"><i class="ion-plus fonts site-red"></i> Add New Database</a>
		<hr>
		<div class="row dash-row">
			
			<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
			<?php endif ?>

			<!-- START Databases -->
			<div class="col-md-1 site-red">
			S/N
			</div>
			<div class="col-md-7 site-red">
			Database
			</div>
			<div class="col-md-1 site-red">
			Code
			</div>
			<div class="col-md-1 site-red">
			Type
			</div>
			<div class="col-md-2 site-red">
			Actions
			</div>
			<hr>
			
			<?php if(!empty($Databases)) :?>
			<?php foreach($Databases as $key => $data) :?>
			<div class="col-md-1 site-init">
			<?php echo $key + 1 ?>
			</div>

			<div class="col-md-7 site-init">
			<a class="site-init" href="<?php echo geturl("admin/databasetables/{$data['id']}?assign=true") ?>"> <?php echo strtoupper( $data['databasename'] ) ?> </a>
			</div>

			<div class="col-md-1 site-init">
			<?php echo strtoupper($data['shortcode']) ?>
			</div>

			<div class="col-md-1 site-init">
			<?php echo strtoupper($data['type']) ?>
			</div>

			<div class="col-md-2">
			<a href="#" onclick='deletePromptAdmin("<?php echo geturl('admin/database?action=drop&id='.$data['id'] ) ?>")' 
			class="site-init action-btn">
			<i class="ion-ios-trash fonts site-red"></i></a>
			<a href="<?php echo geturl('admin/editdatabase?id='.$data['id'] ) ?>" class="site-init action-btn">
			<i class="ion-edit fonts site-red"></i></a>
			</div>

			<div class="col-md-12">
			<hr class="split-list">
			</div>

			<?php endforeach ?>
			<?php else :?>
			<div class="notify">Database List Empty!</div>
			<?php endif ?>

		</div>
		<!-- END Databases -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/adminfooter.phtml') ?>
<!-- END FOOTER