<!--HEADER -->
<?php include('partials/adminheader.phtml') ?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include('partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include("partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<h4 class="site-init inline">Catergory Of Aggregation</h4>
	<a href="<?php echo geturl("admin/categoryaggregation") ?>" class="site-init action-btn pull-right">
		<i class="ion-ios-arrow-back fonts site-red"></i> Go Back</a>
		<hr>
		<div class="row">
		<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
		<?php endif ?>

		<h5 class="site-init text-center">Edit Category Details</h5> 

		<!-- ADD NEW DATABASE -->
		<form class="form-horizontal" method="post" action="">
			<div class="col-md-10" id="logindiv">
			<input type="hidden" name="id" value="<?php echo $Category['id'] ?>">
				<input type="text" class="form-control" name="category" value="<?php echo $Category['category_aggregation_name'] ?>" required 
				placeholder="Catergory Name"/>
				
				<input type="text" class="form-control" name="code" value="<?php echo $Category['code'] ?>" required placeholder="Code"/>

				<select name="levels[]" required multiple class="form-control chosentable aggtables" data-placeholder="Select Level">
					<?php foreach($Levels as $level) :?>
					<option <?php echo in_array($level['id'],$Category['levels']) ? "selected" : ""?> value="<?php echo $level['id'] ?>">
					<?php echo $level['level_aggregation_name'] ?>
					</option>
					<?php endforeach ?>
				</select>
					
					<!-- SELECT ALL -->
					<div class="col-md-6">
						<div class="checkbox site-init font12">
							<label>
								<input type="checkbox" name="selectalltable" value="yes"> Click to select all levels
							 </label>
						</div>
					</div>

					<div class="col-md-6 nopad">
						<div class="checkbox site-init font12">
							<label>
								<input type="checkbox" name="deselectalltable" value="yes"> Click to deselect all levels
							 </label>
						</div>
					</div>
				<!-- END -->

			</div>

			<div id="submitdiv" class="col-md-10">
				<button  class="btn button-custom btn-custom-two pull-right">Update Details</button>
			</div>
		</form>
		<!-- END DATABASE -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/adminfooter.phtml') ?>
<!-- END FOOTER