<!--HEADER -->
<?php include('partials/adminheader.phtml') ?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include('partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include("partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<h4 class="site-init inline">Variables</h4>
	<a href="<?php echo geturl("admin/variables") ?>" class="site-init action-btn pull-right">
		<i class="ion-ios-arrow-back fonts site-red"></i> Go Back</a>
		<hr>
		<div class="row">
		<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
		<?php endif ?>

		<h5 class="site-init text-center">Edit Variable</h5> 

		<!-- ADD NEW DATABASE -->
		<form class="form-horizontal" method="post" action="">
			<div class="col-md-12" id="logindiv">
				<div class="col-md-10 nopad">

				<input type="hidden" name="id" value="<?php echo $Variable['id'] ?>">
				<input type="text" class="form-control" name="variable" value="<?php echo $Variable['variable_name'] ?>" required 
				placeholder="Variable name"/>
						
						<input type="text" class="form-control" name="code" value="<?php echo $Variable['code'] ?>" required placeholder="Code"/>
						
						<!-- ADD TABLE -->
						<select name="table" required class="form-control">
						<option value="">Select Table</option>
						<?php foreach($Tables as $table) :?>
						<option <?php echo ($Variable['table_id'] == $table['id']) ? 'selected' : '' ?> value="<?php echo $table['id'] ?>">
						<?php echo $table['table_name'] ?></option>
						<?php endforeach ?>
						</select>

						<!-- ADD LEVEL OF AGGREGATION -->
						<select name="level" required class="form-control">
						<option value="">Select Level</option>
						<?php foreach($Aggregations as $level) :?>
						<option <?php echo ($Variable['level_aggregation_id'] == $level['id']) ? 'selected' : '' ?> value="<?php echo $level['id'] ?>">
						<?php echo $level['level_aggregation_name'] ?></option>
						<?php endforeach ?>
						</select>
					</div>
			</div>

			<div id="" class="col-md-10">
				<button  class="btn button-custom btn-custom-two pull-right">Update Detail</button>
			</div>
		</form>
		<!-- END DATABASE -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/adminfooter.phtml') ?>
<!-- END FOOTER