<select data-placeholder="Select Frequency Of Data..." required class="chosentable dfrequency" name="frequency" tabindex="3">
	<option value=""></option>
	<!-- <option value="daily">Daily</option>
	<option value="weekly">Weekly</option>
	<option value="monthly">Monthly</option>
	<option value="quaterly">Quarterly</option>
	<option value="yearly">Yearly</option>
 -->
	<?php if(count($Frequencies) > 0) :?> 
	<?php foreach($Frequencies as $frequency) :?>
	<option data-id="<?php echo $frequency['id']?>" data-type="<?php echo strtolower($frequency['frequency_data_name']) ?>" value="<?php echo $frequency['code']?>">
	<?php echo $frequency['frequency_data_name']?></option> 
	 <?php endforeach ?> 
	<?php endif ?>

</select>