<div class="col-md-12 margin-top-1 periodbox" id="logindiv">
		<label for="from" class="col-md-2 site-init">From</label>
		<div class="col-md-4">
		<input type="text" required class="form-control datepicker" name="from" id="from" placeholder="mm/dd/YYYY" >
		</div>
		<label for="to" class="col-md-2 site-init">To</label>
		<div class="col-md-4">
		<input type="text" required class="form-control datepicker" name="to" id="to" placeholder="mm/dd/YYYY" >
		</div>
</div>