<!--HEADER -->
<?php include('partials/adminheader.phtml') ?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include('partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include("partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<h4 class="site-init inline">Requests</h4> 

	<div class="col-md-12 nopad" id="sortdiv">
		<form class="form-horizontal" action="<?php echo geturl('admin/requests') ?>" method="get">
		<input type="hidden" value="sort" name="for" />
		<div class="form-group nopad" id="logindiv">
		<div class="col-md-4">
			<select name="affiliate" class="form-control">
				<option value="">By Instituition</option>
				<?php foreach($Affiliates as $data) :?>
				<option value="<?php echo $data['id'] ?>"><?php echo $data['affiliate_name'] ?></option>
				<?php endforeach ?>
			</select>
		</div>

		<div class="col-md-2">
			<select name="type" class="form-control">
				<option value="">Type</option>
				<option value="affiliate">Affiliated</option>
				<option value="personal">Independent</option>
			</select>
		</div>

		<div class="col-md-2">
			<select name="status" class="form-control">
				<option value="">Status</option>
				<option value="1">Treated</option>
				<option value="0">Not Treated</option>
			</select>
		</div>

		<div class="col-md-2 noleftpad">
			<select name="approved" class="form-control">
				<option value="">Approval</option>
				<option value="YES">Approved</option>
				<option value="NO">Not Approved</option>
			</select>
		</div>

		<button type="submit" title="Filter request" class="nopad">
		<i class="ion-funnel fonts"></i> 
		</button>

		<a href="<?php echo geturl('admin/requests') ?>" title="Clear all filters" class="site-init">
		<i class="ion-android-funnel fonts"></i> 
		</a>

		</div>

		</form>


		<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify text-center font12"><?php echo $notification ?></div>
		<?php endif ?>

	</div>

	<br>
		<div class="row dash-row">
			
			<div class="col-md-12">
			<!-- START Databases -->
			<div class="col-md-1 nopad text-left site-red font12">
			S/N
			</div>
			<div class="col-md-2 text-left nopad site-red font12">
			Request
			</div>
			<div class="col-md-3 text-left nopad site-red font12">
			Instituition
			</div>
			
			<div class="col-md-2 site-red font12">
			Date
			</div>

			<div class="col-md-1 site-red font12">
			Approved
			</div>

			<div class="col-md-1 site-red font12">
			Status
			</div>
			
			<div class="col-md-2 site-red font12">
			Actions
			</div>
			<hr>
			</div>
			
			<?php if(!empty($Requests)) :?>
			<?php foreach($Requests as $key => $Request) :?>
			<div class="col-md-1 site-init">
			<?php echo $key + 1 ?>
			</div>

			<div class="col-md-2 site-init">
			<?php echo strtoupper( $Request['code'] ) ?>
			</div>

			<div class="col-md-3 nopad site-init">
			<?php echo !empty($Request['affiliate_name']) ? strtoupper($Request['affiliate_name']) : "Not Specified" ?> 
			</div>
			
			<!-- <div class="col-md-1 site-init"><?php //echo ($Request['affiliate_id'] != 0) ? 'Affilaited' : 'Independent' ?>
			</div> -->
			
			<div class="col-md-2 nopad site-init">
			<?php echo date_create($Request['created_at'])->format('d M Y  h:i:s') ?>
			</div>

			<div class="col-md-1 site-init text-center"><?php echo ($Request['approved']) ?>
			</div>

			<div class="col-md-1 site-init"><?php echo ($Request['status'] == 1) ? 
			"<i title='Treated' class='ion-ios-checkmark-outline fonts green'></i>"
			: " <i title='Not Treated' class='ion-ios-close-outline fonts site-red'></i>" ?>
			</div>

			<div class="col-md-2">
			<a title="delete request" href="#" 
			onclick='deletePromptAdmin("<?php echo geturl('admin/requests?action=drop&id='.$Request['id'] ) ?>")' class="site-init action-btn">
			<i class="ion-ios-trash fonts site-red"></i></a>
			<a title="view request" href="<?php echo geturl('admin/requests?action=view&id='.$Request['id'] ) ?>
			" class="site-init action-btn">
			<i class="ion-eye fonts site-red"></i></a>
			</div>

			<div class="col-md-12">
			<hr class="split-list">
			</div>

			<?php endforeach ?>
			<div class="col-md-12">
				<?php echo $Links ?>
			</div>
			<?php else :?>
			<div class="col-md-12">
			  <div class="notify row">Requests List Empty!</div>
			</div>
			<?php endif ?>

		</div>
		<!-- END Databases -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/adminfooter.phtml') ?>
<!-- END FOOTER