<!--HEADER -->
<?php include('partials/adminheader.phtml') ?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include('partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include("partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<h4 class="site-init inline">Tables</h4> 
	<a href="<?php echo geturl('admin/database') ?>"class="site-init action-btn pull-right">
	<i class="ion-ios-arrow-back fonts site-red"></i>Go Back</a>

	<?php if($_GET['assign']): ?>

		<?php if(!empty($Tables)): ?>
		<a href="<?php echo geturl("admin/reassigntables/{$database_id}?assigntables=true") ?>"class="site-init action-btn pull-right">
		<i class="ion-plus fonts site-red"></i> Edit Database Tables
		</a>
		<?php else: ?>
		<a href="<?php echo geturl("admin/databasetables/{$database_id}?assigntables=true") ?>"class="site-init action-btn pull-right">
		<i class="ion-plus fonts site-red"></i> Assign Tables
		</a>
		<?php endif ?>
	<?php else: ?>
	<a href="<?php echo geturl("admin/addtables") ?>"class="site-init action-btn pull-right">
	<i class="ion-plus fonts site-red"></i> Add Tables
	</a>
	<?php endif ?>

		<hr>
		<div class="row dash-row">
			
			<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
			<?php endif ?>

			<!-- START TABLES -->
			<div class="col-md-1 site-red">
			S/N
			</div>
			<div class="col-md-8 site-red">
			Table Name
			</div>
	
			<?php if(!$_GET['assign']): ?>
			<div class="col-md-2 site-red">
			Actions
			</div>
			<?php endif ?>

			<hr>
			
			<?php if(!empty($Tables)) :?>
			<?php foreach($Tables as $key => $table) :?>
			<div class="col-md-1 site-init">
			<?php echo $key + 1 ?>
			</div>

			<div class="col-md-8 site-init">
			<?php echo strtoupper($table['table_name']) ?>
			</div>
			
			<?php if(!$_GET['assign']): ?>
			<div class="col-md-2">
			<a href="<?php echo geturl('admin/editable/'.$table['id'] ) ?>" class="site-init action-btn">
			<i class="ion-edit fonts site-red"></i></a>
			<a href="#" onclick='deletePromptAdmin("<?php echo geturl('admin/tables?action=drop&id='.$table['id'] ) ?>")' 
			class="site-init action-btn">
			<i class="ion-ios-trash fonts site-red"></i></a>
			</div>
			<?php endif ?>

			<div class="col-md-12">
			<hr class="split-list">
			</div>

			<?php endforeach ?>
			<?php else :?>
			<div class="notify">Tables List Empty!</div>
			<?php endif ?>

		</div>
		<!-- END AFFILIATES -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include('partials/adminfooter.phtml') ?>
<!-- END FOOTER