
<select data-placeholder="Select Tables..." class="chosentable dtable" required tabindex="3" name="table">
	<option value=""></option>
	<?php if(count($Tables) > 0) :?>
	<?php foreach($Tables as $table) :?>
		<option data-id="<?php echo $table['id']?>" value="<?php echo $table['code']?>"> <?php echo $table['table_name']?> </option>
	<?php endforeach ?>
	<?php else :?>
		<option value="">No results returned!</option>
	<?php endif ?>
</select>
