<select data-placeholder="Select Variables From Table..." required class="chosentable dvariable" multiple="" tabindex="3" name="variable[]">
	<option value=""></option>
	<?php if(count($Variables) > 0) :?>
	<!-- <option value="selectall" id="select_all">Select All</option> -->
	<!-- <option value="deselectall" id="deselect_all">Deselect All</option> -->
	<?php foreach($Variables as $variable) :?>
		<option value="<?php echo $variable['code']?>"><?php echo $variable['variable_name']?></option>
	<?php endforeach?>
	<?php else :?>
		<option value="">No results returned!</option>
	<?php endif ?>
</select>

<div class="col-md-6">
	<div class="checkbox site-init font12">
		<label>
			<input type="checkbox" name="selectall" value="yes"> Click to select all variables
		 </label>
	</div>
</div>

<div class="col-md-6">
	<div class="checkbox site-init font12">
		<label>
			<input type="checkbox" name="deselectall" value="yes"> Click to deselect all variables
		 </label>
	</div>
</div>