<!--HEADER -->
<?php
$viewpath = config('view_path');
include($viewpath.'/partials/adminheader.phtml');
?>
<!-- END HEADER -->

<!-- MENU SECTION -->
<?php include($viewpath.'partials/backendmenu.phtml') ?>
<!--MENU SECTION END-->


<!--HOME SECTION END-->
<!--SERVICE SECTION START-->
<br>
<br>
<section id="services" >
<div class="container">
<div class="row text-center header">
<!-- <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 animate-in" data-anim-type="fade-in-up">
<h3 style="margin:0px;">REQUEST DATA</h3>
<hr style="margin-top:5px !mportant;margin-bottom:0px"/>
</div> -->
</div>
<div class="row animate-in" data-anim-type="fade-in-up">

<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
	<?php include($viewpath."partials/adminmenu.phtml") ?>
</div>

<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8 main-body">
	<div class="services-wrapper">
	<ol class="breadcrumb">
			<li><a href="<?php echo geturl('admin/dashboard')?>">Dashboard</a></li>
			<li><a href="<?php echo geturl('admin/categoryaggregation')?>">Category</a></li>
			<li class="active">Add-New</li>
		</ol>
		<hr>
		<div class="row">
		<?php if(isset($notification) && !empty($notification)) :?>
			<div class="notify"><?php echo $notification ?></div>
		<?php endif ?>

		<!-- ADD NEW Catergory -->
		<form class="form-horizontal" method="post" action="">
			<div class="col-md-8" id="logindiv">
					<input type="text" class="form-control" name="category" required placeholder="Catergory name"/>
			</div>
				
			<div class="col-md-2 col-md-offset-1" id="logindiv">
				<input type="text" class="form-control" name="code" required placeholder="Code"/>
			</div>

			<div class="col-md-8">
				<select name="levels[]" required multiple class="form-control chosentable aggtables" data-placeholder="Select Level">
					<?php foreach($Levels as $level) :?>
					<option value="<?php echo $level['id'] ?>"><?php echo $level['level_aggregation_name'] ?></option>
					<?php endforeach ?>
				</select>
			</div>
			
			<div class="col-md-8 coverbd">
				<!-- SELECT ALL -->
					<div class="col-md-6">
						<div class="checkbox site-init font12">
							<label>
								<input type="checkbox" name="all" value="yes"> Select All Levels
							 </label>
						</div>
					</div>

					<div class="col-md-6 nopad">
						<div class="checkbox site-init font12">
							<label>
								<input type="checkbox" name="notall" value="yes">Deselect All Levels
							 </label>
						</div>
					</div>
				<!-- END -->
			</div>

			<div id="submitdiv" class="col-md-12">
			<br>
				<button  class="btn button-custom btn-custom-two">Add</button>
			</div>
				
			</div>

			
		</form>
		<!-- END Catergory -->

	</div>
</div>



</div>
</div>
</section>



<!--CONTACT SECTION START-->
<!--CONTACT SECTION END-->

<!-- FOOTER -->
<?php @include($viewpath.'partials/footer.phtml') ?>
<!-- END FOOTER